services:
  poller:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: python mijia.py

  bot:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: python bot.py

  celery:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: celery -A tasks worker --loglevel=info

  celery-beat:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: celery -A tasks beat --loglevel=info