apiVersion: apps/v1
kind: Deployment
metadata:
  name: mijia-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mijia
      component: redis
  template:
    metadata:
      labels:
        app: mijia
        component: redis
    spec:
      containers:
        - name: redis
          image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: mijia-redis
spec:
  type: ClusterIP
  ports:
    - name: mijia
      port: 6379
  selector:
    app: mijia
    component: redis