name: set-environment
description: 'Set environment variables for the action'
inputs:
  secret_key:
    description: 'Secret key'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        touch .env
        echo SECRET_KEY=${{ inputs.secret_key }} >> .env
        cat .env
      shell: bash